update_fastlane

default_platform(:mac)

platform :mac do
  
  xcode_select "/Applications/Xcode.app"

  lane :release do
    sh("yarn", "bump")

    version = get_version_number(xcodeproj: "./macos/sol.xcodeproj")

    path = "/Users/osp/Developer/sol/releases/"
    appFileName = path + "Sol.app"
    zipFileName = path + version + ".zip"
    
    gym(
      scheme: "macOS",
      configuration: "Release",
      clean: true,
      workspace: "./macos/sol.xcworkspace",
      output_directory: path,
      export_method: "developer-id"
    )

    notarize(
      package: appFileName,
      bundle_id: "com.ospfranco.sol",
      asc_provider: "24CMR7378R"
    )

    sh("zip", "-r", zipFileName, appFileName)

    # zip(
    #   path: appFileName,
    #   output_path: zipFileName
    # )

    sh("yarn", "appcast")

    # sh("git", "add", "..")
    # sh("git", "commit", "-m", '"' + version + '"')
    # sh("git", "push")

    sh("pingme")
  end

  lane :dev do
    path = "/Applications/"

    gym(
      scheme: "macOS",
      workspace: "./macos/sol.xcworkspace",
      output_directory: path,
      export_method: "development",
      silent: true
    )
  end
end
