# update_fastlane

default_platform(:mac)

platform :mac do
  lane :release do
    outputPath = "/Users/osp/Developer/"
    appFileName = outputPath + "Sol.app"
    zipFileName = outputPath + "Sol.zip"
    
    build_mac_app(
      scheme: "macOS",
      configuration: "Release",
      workspace: "./macos/sol.xcworkspace",
      output_directory: outputPath,
      export_method: "developer-id",
      silent: true
    )

    notarize(
      package: appFileName,
      bundle_id: "com.ospfranco.sol",
      asc_provider: "24CMR7378R"
    )

    zip(
      path: appFileName,
      output_path: zipFileName
    )
  end

  lane :dev do
    outputPath = "/Applications/"
    appFileName = outputPath + "Sol.app"

    build_mac_app(
      scheme: "macOS",
      workspace: "./macos/sol.xcworkspace",
      output_directory: outputPath,
      export_method: "development",
      silent: true
    )
  end
end
