update_fastlane

default_platform(:mac)

platform :mac do
  
  xcode_select "/Applications/Xcode.app"

  lane :release do
    sh("yarn", "bump")

    version = get_version_number(xcodeproj: "./macos/sol.xcodeproj")

    outputPath = "/Users/osp/Developer/sol/releases/"
    appFileName = outputPath + "Sol.app"
    zipFileName = outputPath + version + ".zip"
    
    gym(
      scheme: "macOS",
      workspace: "./macos/sol.xcworkspace",
      output_directory: outputPath,
      export_method: "developer-id"
    )

    notarize(
      package: appFileName,
      bundle_id: "com.ospfranco.sol",
      asc_provider: "24CMR7378R",
      verbose: true
    )

    zip(
      path: appFileName,
      output_path: zipFileName
    )

    sh("yarn", "appcast")

    # sh("git", "add", "..")
    # sh("git", "commit", "-m", '"' + version + '"')
    # sh("git", "push")

    sh("pingme")
  end

  lane :dev do
    outputPath = "/Applications/"
    appFileName = appFileName

    gym(
      scheme: "macOS",
      workspace: "./macos/sol.xcworkspace",
      output_directory: outputPath,
      export_method: "development",
      silent: true
    )
  end
end
